// Generated by しくみや — 2026-04-02T19:29:08.967Z
export const siteConfig = {
  name: "Lyo",
  siteTitle: "Lyo — Gallery",
  description: "世界の破壊",
  url: "",
  lang: "ja",
  template: "minimal-grid",

  colors: {
    primary: "#00e5ff",
    accent: "#d4a853",
    background: "#0a0a0f",
  },

  hero: {
    tagline: "Gallery",
    catchcopy: "いっぱいおもちゃ",
    motto: "世の中は理不尽だ",
    subtitle: "Art Portfolio",
    description: "世界の破壊",
    backgroundImage: "/images/hero.webp",
    cta: {
      text: "作品を見る",
      href: "#gallery",
    },
  },

  gallery: {
    title: "GALLERY",
    subtitle: "作品ギャラリー",
    description: "",
    works: [
    { src: "/images/work_01.webp", title: "作品 01", description: "" },
    { src: "/images/work_02.webp", title: "作品 02", description: "" },
    { src: "/images/work_03.webp", title: "作品 03", description: "" },
    ],
    initialDisplay: 8,
  },

  about: {
    title: "ABOUT",
    subtitle: "アーティストについて",
    image: "/images/about.webp",
    paragraphs: ["世界の破壊"],
    quote: "世の中は理不尽だ",
    genres: ["イラスト","AIアート"],
    tools: ["Stable Diffusion","ComfyUI","Midjourney"],
  },

  contact: {
    title: "CONTACT",
    subtitle: "お問い合わせ・SNS",
    description: "お仕事のご依頼・コラボレーション・ご質問はお気軽にどうぞ。",
    email: "ryoya112@outlook.com",
    social: [

    ],
  },

  nav: [
    { label: "Gallery", href: "#gallery" },
    { label: "About", href: "#about" },
    { label: "Contact", href: "#contact" },
  ],

  footer: {
    credit: "Built with Next.js — Template by しくみや",
    copyright: `© ${new Date().getFullYear()} Lyo. All rights reserved.`,
  },
};

export type SiteConfig = typeof siteConfig;
